[tool.poetry]
name = "tapir"
version = "0.1.0"
description = ""
authors = ["Leon Handreke <leonh@ndreke.de>"]

[tool.poetry.dependencies]
python = "^3.10"
Django = "~3.2.16"
django-ldapdb = { version = "^1.5.1", markers = "sys_platform=='linux' or sys_platform=='darwin'" }
django-weasyprint = "^2.2.0"
django-extensions = "^3.2.1"
django-bootstrap-datepicker-plus = "^4.0.0"
psycopg2 = "^2.9.5"
django-tables2 = "^2.5.1"
django-filter = "^22.1"
tablib = "^3.3.0"
django-phonenumber-field = "^7.0.2"
phonenumbers = "^8.13.4"
weasyprint = "^57.2"
django-select2 = "^7.11.1"
django-silk = "^5.0.3"
gunicorn = "^20.1.0"
django-environ = "^0.9.0"
django-bootstrap5 = "^22.2"
djangorestframework = "3.13.1"
djangorestframework-simplejwt = "5.2.0"
django-cors-headers = "3.11.0"
celery = "^5.2.7"
redis = "^4.4.2"
ipython = "^8.8.0"
django-chartjs = "^2.3.0"
unidecode = "^1.3.6"
python-barcode = "^0.14.0"

[tool.poetry.group.dev.dependencies]
black = "^22.12.0"
ipython = "^8.8.0"
pre-commit = "^2.21.0"
werkzeug = "^2.2.2"
pytest = "^7.2.1"
pytest-cov = "^4.0.0"
pytest-django = "^4.5.2"
pytest-sugar = "^0.9.6"
selenium = "^4.7.2"
factory-boy = "^3.2.1"
poetryup = "^0.12.7"
djlint = "^1.19.16"

[tool.djlint]
profile = "django"
max_line_length = 120
ignore = "T002,H006,H021,H025,H030,H031"
use_gitignore = true

[build-system]
requires = ["poetry-core>=1.2.0"]
build-backend = "poetry.core.masonry.api"
